### ISSUE TITLE
Destroy Terminal Shortcut

### ISSUE THREAD

**Issue by NestorAlbelo** [thedaniel/terminal-panel#14]
Hi, I was looking for in your documentation how to destroy the current terminal, but I did not find anything, so I download the code to try implement it by myself and I saw that you had already implement that with:
'cmd-shift-x': 'terminal-panel:destroy'

I just want to notice you that the Readme is not updated and I want to thank for building this great feature =D

**Comment by braver** [comment]
Thanks! fixed in https://github.com/thedaniel/terminal-panel/commit/76f03d8c1dffb2b9f65eaae264f9e4d1ca5cf3a8
