### ISSUE TITLE
FeatureReq : stderr

### ISSUE THREAD

**Issue by alanzanattadev** [thedaniel/terminal-panel#20]
Hey, can you add the stderr to the output please ? Thank's ;)

**Comment by braver** [comment]
The current implementation of the terminal doesn't allow some of the more advanced features of a full fledged interactive terminal. A bug in a node module has prevented moving toward a more advanced terminal. For the foreseeable future we're sticking to this. If a more advanced implementation happens your wish may  be granted, but for now we're closing this and similar issues as beyond the current scope.
