### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by ginus** [thedaniel/terminal-panel#21]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (c:\Users\Administrator\AppData\Local\atom\app-0.174.0\resources\app\src\atom.js:55:11)
CliStatusView.attach (c:\Users\Administrator\.atom\packages\terminal-panel\lib\cli-status-view.coffee:58:9)
```

**Comment by thedaniel** [comment]
thanks for the bug report
