### ISSUE TITLE
terminal-panel throws error when trying to open on Ubuntu 14.04 atom v-0.174.0

### ISSUE THREAD

**Issue by sedabull** [thedaniel/terminal-panel#24]
I get the following error when trying to open up a terminal-panel:
![terminal_panel_error](https://cloud.githubusercontent.com/assets/9311295/5812269/bc1b3fce-a034-11e4-8e9b-9f9ff214c770.png)
I believe the error is coming from lib/command-output-view.coffee in the initialize method, however I'm not familiar enough with the atom api yet to create a patch. I'm not entirely sure what a disposable is, or how to use it correctly.

EDIT: This error renders this package entirely unusable, which is disappointing, because it's a major part of my workflow.

**Comment by rnyberg** [comment]
I can verify. Happends with only terminal-panel installed (along with default packages), with a fresh Atom and a fresh Ubuntu 14.04.
