### ISSUE TITLE
Shift-Enter does not work (OS X)

### ISSUE THREAD

**Issue by cliffrowley** [thedaniel/terminal-panel#30]
Not sure if it's just OS X, but shift-enter simply enters a new line in the current document rather than toggling the terminal panel.  The command works fine if run through the command palette, so it's just the shortcut.

**Comment by braver** [comment]
fixed in https://github.com/thedaniel/terminal-panel/commit/a4f0ed86338aadd02795fc254719f36a6fc6b2b7
