### ISSUE TITLE
We need a auto-complete shortcut

### ISSUE THREAD

**Issue by pdroalves** [thedaniel/terminal-panel#34]
Currently, when i'm writing something on terminal and hit "tab", it just loses focus. 

We **must have** some shortcut to apply an autocomplete behaviour.

**Comment by Rask** [comment]
+1.

`cd`ing through the file system is one hell because we can't use autocompletion.

**Comment by braver** [comment]
Yes, we would **like to have** this feature.

**Comment by braver** [comment]
closing this in favour of #8
