### ISSUE TITLE
Display bug

### ISSUE THREAD

**Issue by gaetanm** [thedaniel/terminal-panel#35]
![screen shot 2015-02-26 at 14 47 52](https://cloud.githubusercontent.com/assets/2548394/6392996/79bd9f28-bdc6-11e4-822e-e3a6ae1f5aa5.png)

If I enter like 3 times the `ls` command, the console is firstly resized (I guess it's a normal behaviour) but then the output go outside the console.

**Comment by braver** [comment]
I can't reproduce this in the current version. Do you have any more information, or something that could point to the problem?

**Comment by braver** [comment]
It's been over a year...
