### ISSUE TITLE
adds a ton to startup time.

### ISSUE THREAD

**Issue by thedaniel** [thedaniel/terminal-panel#4]
239 ms on my beast macbook pro :(

**Comment by braver** [comment]
These days it's not so bad (11" i7 Macbook Air)
![screen shot 2015-05-06 at 21 52 07](https://cloud.githubusercontent.com/assets/2543659/7502155/2e7ed8a6-f43a-11e4-9944-5d323f91abc3.png)

**Comment by zephraph** [comment]
![image](https://cloud.githubusercontent.com/assets/3087225/7569223/e8eccc76-f7cc-11e4-9be5-0af40440eeb9.png)

Latest version on Windows.

**Comment by braver** [comment]
Is that directly after you updated? I think it should drop after a reload (after caching the code). It's still a concern though.
