### ISSUE TITLE
Hotkey configuration

### ISSUE THREAD

**Issue by RangerMauve** [thedaniel/terminal-panel#5]
It seems that there are no hotkey configuration options in the settings, and the defaults conflict with a different plugin that I'm using. It'd be nice if this was fixed.

**Comment by braver** [comment]
Read all about it: https://atom.io/docs/latest/behind-atom-keymaps-in-depth  
If you want to change keybindings, you can do so in your keymap. It's not perfect, but it's the only way out of the jungle that actually works.
