### ISSUE TITLE
Package.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by angelbotto** [thedaniel/terminal-panel#52]
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `terminal-panel` package
```
Package.getStylesheetsPath (/Applications/Atom.app/Contents/Resources/app/src/package.js:430:9)
Package.getStylesheetPaths (/Applications/Atom.app/Contents/Resources/app/src/package.js:441:32)
```

**Comment by braver** [comment]
fixed in https://github.com/thedaniel/terminal-panel/commit/b061360a19a6fb422d21ffdc9737344df08544a9
