### ISSUE TITLE
Scrollable screens instead of dumping the whole output of a file

### ISSUE THREAD

**Issue by Rask** [thedaniel/terminal-panel#55]
Certain commands display a file in a scrollable terminal view (e.g. `git log`).

Currently terminal-panel just reads the contents and dumps them to STDOUT. This makes me need to wade through thousands of commits when using `git log` if I want to see the *latest* commits.

Would scrollable outputs be possible to create?

**Comment by braver** [comment]
The current implementation of the terminal doesn't allow some of the more advanced features of a full fledged interactive terminal. What you're asking here is beyond the scope of the current implementation. 

You can however limit the output of the log command (e.g. `git log -3`)
