### ISSUE TITLE
A 1px black bar is added every time I open and close the panel.

### ISSUE THREAD

**Issue by AlexanderOMara** [thedaniel/terminal-panel#63]
I don't believe this issue was present in the previous version, but with the latest version (1.11.0), every time I open and close the terminal panel, an additional 1px black bar in added above the bottom tool panel. Since another 1px is added every time, it adds up to lost screen space, and destroying the terminal does not remove them.

Here are some pictures of how it looks and the DOM nodes causing it.

![view](https://i.imgur.com/psBNOlW.png)

![DOM](https://i.imgur.com/gzDJUPF.png)

**Comment by braver** [comment]
This is a bug, but it's also there in `1.10.0`. Will look into it, a bunch of this has to be reworked for 1.0 anyway.
