### ISSUE TITLE
Locks up when I use 'git push origin master'

### ISSUE THREAD

**Issue by zachdyer** [thedaniel/terminal-panel#69]
Sometimes it locks up when I do certain commands. Anyone else have this issue?

**Comment by braver** [comment]
The terminal isn't interactive, so it can lock up if a process needs your input. You should be able to kill it though.

**Comment by zachdyer** [comment]
Why is it not interactive?

**Comment by braver** [comment]
You can read more about that in #3

**Comment by braver** [comment]
I'm going to close this as beyond scope right now. It is something that has our attention though.
