### ISSUE TITLE
FeatureReq : Command History.

### ISSUE THREAD

**Issue by v3ss0n** [thedaniel/terminal-panel#7]
Would be nice to have command history like bash_history.

**Comment by malexandre** [comment]
+1

**Comment by sedabull** [comment]
+1

**Comment by SeanBlader** [comment]
+1 more, this would be amazingly helpful

**Comment by v3ss0n** [comment]
Yes its quite easy to do. If i liked coffeescript .

**Comment by braver** [comment]
this should be fixed in https://github.com/thedaniel/terminal-panel/pull/57
