### ISSUE TITLE
Design align broken on atom 0.200.0

### ISSUE THREAD

**Issue by raphagodoi** [thedaniel/terminal-panel#71]
I've installed the latest version of atom and the terminal alignment is broken / strange.

![captura de tela 2015-05-20 as 14 29 34](https://cloud.githubusercontent.com/assets/3275387/7732252/d51ac72a-fefc-11e4-86a3-d41e3685ec0a.png)

**Comment by braver** [comment]
Do you mean the ls output? What is weird exactly?

**Comment by braver** [comment]
I don't see a problem and would need more info to do anything
