### ISSUE TITLE
with the latest update is breaking other packages

### ISSUE THREAD

**Issue by skandasoft** [thedaniel/terminal-panel#72]
I found that on enabling terminal-panel I am not able to click on the link in the browser(browser-plus http://atom.io/packages/browser-plus). I am not sure what changes you made..

**Comment by braver** [comment]
I don't know of such a problem or anything that points to terminal-panel causing problems in other packages. I would love to debug this, but your browser-plus package will not install (https://github.com/skandasoft/browser-plus/issues/7)

**Comment by braver** [comment]
I cannot reproduce any problems in the current version
