### ISSUE TITLE
No Backtick on German Layout

### ISSUE THREAD

**Issue by mirbach** [thedaniel/terminal-panel#79]
There is no backtick on german keyboard layout. Can't toggle terminal-panel.
Key bindings should be changeable.

**Comment by braver** [comment]
Key bindings are changeable: you can define your own by looking at the commands that are used in the default bindings and configuring your own bindings. 

https://atom.io/docs/v1.0.2/using-atom-basic-customization#customizing-key-bindings

**Comment by mirbach** [comment]
Wow thanks, didn't know that this can be used for packages.

**Comment by braver** [comment]
:+1:
