### ISSUE TITLE
Doesn't show env variables

### ISSUE THREAD

**Issue by hieinji** [thedaniel/terminal-panel#89]
I'm using Atom to develop hybrid mobile apps, since the beginning I needed an opened terminal to launch my applications. Today I decided to integrate a terminal into Atom and after a couple of tries I installed your package. Your plugin is very good but I have a problem, it doesn't display the value of the local environment variables. For example, if I write "echo $ANDROID_HOME" it doesn't display nothing, instead, if I run it in the default ubuntu terminal it displays the location of my android sdk.

Is this a bug or there is a solution to solve this issue? Thank you so much.
hieinji

**Comment by braver** [comment]
This package doesn't expose a full terminal. Instead, it's just an interface to send commands to be executed. If you're looking for a fully integrated terminal, look for packages like [term2](https://atom.io/packages/term2)
