### ISSUE TITLE
[Windows] Cannot type when program is expecting input

### ISSUE THREAD

**Issue by gordonszhang** [thedaniel/terminal-panel#92]
When attempting to run a piece of C++ code that takes user input from the console, the command box disappears altogether and no text can be entered. Is this a Windows only issue? Thanks.

**Comment by chuckcruz** [comment]
This is also happening on Mac :(

**Comment by braver** [comment]
This is a known limitation of the way this package implements terminal commands. There is no interactivity, it just `exec`'s your input. Please refer to https://github.com/thedaniel/terminal-panel/issues/3. If you're looking for an interactive shell integrated into Atom there are a number of options but this isn't one of them.
